Restore the option to build a GTK3 GUI

diff --git a/src/APP/do b/src/APP/do
--- a/src/APP/do
+++ b/src/APP/do
@@ -26,7 +26,7 @@ echo "./do complete           # compile, link all."
 echo "./do                    # start gcad3d in local-test-environment"
 echo "---------------------------------------------------------------------"
 echo "./do gui-gtk2           # set GUI gtk2"
-#echo "./do gui-gtk3           # set GUI gtk3"
+echo "./do gui-gtk3           # set GUI gtk3"
 echo "./do guiinit            # recompile all sources of active GUI-version"
 echo "./do gui                # rebuild xa_gui_gtk-*.so"
 echo "./do guiexe             # rebuild executables GUI_*"
@@ -108,11 +108,11 @@ if [ $? -ne 0 ]; then
   echo "****** ERROR build gui-gtk2 *******"
   exit 1
 fi
-#./do gui-gtk3
-#if [ $? -ne 0 ]; then
-#  echo "****** ERROR build gui-gtk3 *******"
-#  exit 1
-#fi
+./do gui-gtk3
+if [ $? -ne 0 ]; then
+  echo "****** ERROR build gui-gtk3 *******"
+  exit 1
+fi
 # rebuild executables GUI_*
 ./do guiexe
 if [ $? -ne 0 ]; then
@@ -265,16 +265,16 @@ fi
 fi
 
 
-#if test "$1" = "gui-gtk3"; then
-## test if gtk3 installed and set as active gui-version
-#../gui_version_set.sh gtk3
-#if [ $? -ne 0 ] ; then
-#  exit 1
-#fi
-## compile ..
-#./do guiinit
-#  exit $?
-#fi
+if test "$1" = "gui-gtk3"; then
+# test if gtk3 installed and set as active gui-version
+../gui_version_set.sh gtk3
+if [ $? -ne 0 ] ; then
+  exit 1
+fi
+# compile ..
+./do guiinit
+  exit $?
+fi
 
 
 if test "$1" = "guiinit"; then
